name: Property Scraper

on:
  workflow_dispatch:
    inputs:
      step:
        description: "Choose step"
        required: true
        default: "step1"
        type: choice
        options:
          - step1
          - step2

      states:
        description: "Comma separated states"
        required: false
        default: "NSW"

      max_properties:
        description: "Max properties"
        required: false
        default: "10"

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Install Playwright Browsers
        run: playwright install --with-deps

      - name: Run Step 1
        run: |
          PYTHONPATH=. python scraper/step1_scrape.py "${{ github.event.inputs.states }}" "${{ github.event.inputs.max_properties }}"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-output
          path: |
            *.csv
            debug/
